### ISSUE TITLE
[Bug] First activity heartbeat not sent right away

### ISSUE THREAD

**Issue by stellarhoof** [temporalio/sdk-typescript#1053]
### What are you really trying to do?

Cancel an activity

### Describe the bug

The first activity heartbeat is throttled, so the activity only gets cancelled after the first heartbeat is sent, which depends on the `heartbeatTimeout`

### Minimal Reproduction

Change the `heartbeatTimeout` in the [activities-cancellation-heartbeating](https://github.com/temporalio/samples-typescript/blob/main/activities-cancellation-heartbeating/src/workflows.ts#L6)] sample code to `10s` and verify that the activity is cancelled only right before the full `10s`

### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: SDK version 1.6.0
- Docker temporal server

**Comment by bergundy** [comment]
The first heartbeat _is_ sent right away, the activity in the sample sleeps and then heartbeats though.
Even if it did heartbeat first, you still might not get the cancellation delivered since that is timing sensitive and depends on when the cancellation is requested by the workflow.

https://github.com/temporalio/samples-typescript/blob/ba6208155bc7b547c76931b7e14e92ce4594af28/activities-cancellation-heartbeating/src/activities.ts#L13
