### ISSUE TITLE
[Feature Request] Permit imports of Node `buffer` module in workflows 

### ISSUE THREAD

**Issue by silasdavis** [temporalio/sdk-typescript#1108]
### Is your feature request related to a problem? Please describe.

It would be useful to permit uses of the builtin `buffer` on the import tree for workflows. 

In my particular case I have parsing logic to convert workflow input types into richer domain types that relies on `buffer`.

### Describe the solution you'd like

I note that all `builtinModules` are included in `disallowedModules`, I'm not sure if this is because you would need to shim them in the v8 isolate explicitly or if it is down to non-determinism issues with `Buffer`. `unsafeAlloc` and friends perhaps?

I would assume otherwise that buffer would be safe to us (I have `BigNumber` implementations depending on it).

The solution I would like is for an exemption to be made similar to that which exists for `assert`.

### Additional context

Incidentally it would be really handy to emit some additional context when reporting problematic modules. The error message lists the modules but not their source, however `data.context` in the callback here:

https://github.com/temporalio/sdk-typescript/blob/2073c5385f92b0927cf745a1fec2845f19a70b10/packages/worker/src/workflow/bundler.ts#L193

Does have access to the module which actually made the call which helps a lot in narrowing down the source of the bad module import.

**Comment by mjameswh** [comment]
After discussion, our team has determined that it's preferable not to provide out-of-the-box support for Node's `Buffer` API, since that goes against some of our mid-term and long-term objectives, notably regarding the possibly of supporting other JavaScript runtimes (eg. Deno, browser, etc).

Instead, we encourage users to load appropriate polyfills from their Webpack bundler. [A sample](https://github.com/temporalio/samples-typescript/issues/280) will soon be added demonstrating how to do so.
