### ISSUE TITLE
[Bug] Pin dependencies

### ISSUE THREAD

**Issue by leeweisberger** [temporalio/sdk-typescript#1131]
There is currently a [bug](https://github.com/streamich/unionfs/issues/765) in the latest release of https://github.com/streamich/unionfs. The `@temporalio/worker` package does not pin this dependency (currently set to `"unionfs": "^4.4.0"`) so the package is unusable causing a company-wide outage for us. This same thing has happened on multiple occasions over the last few months.

This sdk is a core piece of infrastructure and should not suddenly break when indirect dependencies are updated. 

Error code from offending package:
```
Error: Cannot find module 'node_modules/unionfs/lib/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by bergundy** [comment]
Looks like unionfs was fixed here:
https://github.com/streamich/unionfs/commit/708def6c02f1a8795d2754ba814cdf1c433b174c

@mjameswh let’s consider pinning the dependencies.

**Comment by mjameswh** [comment]
>Looks like unionfs was fixed here:

For now, I updated the dependency to jump over the broken release of unionfs.

>This sdk is a core piece of infrastructure and should not suddenly break when indirect dependencies are updated.

>let’s consider pinning the dependencies.

I suppose you mean pinning _all_ dependencies. That's an interesting idea, but I'm not sure how much we can really help on this without causing more damage than we're trying to avoid.

We would need to pin all dependencies of our packages to exact version, as even a patch release can introduce the kind of issue unionfs had. And we would only be able to fix our own direct dependencies, so even by pinning all of our direct dependencies, this kind of situation could still happen because of some transitive dependency (there is no "universal way" to pin _transitive_ dependencies in NPM/package.json world).

I'll have to think about this more. Could be useful to have a look at what other projects have done to avoid similar issues... if any.

**Comment by bergundy** [comment]
I wonder what other packages do here.
I too was thinking that transitive dependencies can’t be pinned. The only way around it is vendoring which I don’t think we want.
We try to minimize our dependencies to avoid situations like this but there’s only so much we can do while we rely on a bundler like webpack.

**Comment by leeweisberger** [comment]
Here's a good discussion: https://docs.renovatebot.com/dependency-pinning/#so-whats-best

TIL the recommendation here is to not pin dependencies to avoid a false sense of security and forcing consumers to confirm multiple versions of the same package.

Thanks for considering, but I'll go ahead and close.
