### ISSUE TITLE
[Support] How to implement a real Authorization workflow inbound interceptor

### ISSUE THREAD

**Issue by YufeeXing** [temporalio/sdk-typescript#1135]
From your official doc
![image](https://github.com/temporalio/sdk-typescript/assets/42690790/9cf3b316-94ec-4d59-b06b-e6d412535206)
If I want to validate the header by a remote authentication service. But in different env, the URL of the authentication service is different.

And for determinism, the 'process' is forbidden in this workflow inbound interceptor. So how to handle this situation?
Look forward to your reply. Thanks.

**Comment by mjameswh** [comment]
One possibility would be to call a local activity from your Workflow inbound interceptor. From that activity, you will be able to access environment variables and make calls to your external auth service.

You will however need to be careful to ensure that no sensitive data get written to the history. Note that, at the moment, TS SDK does not process [headers through Payload codecs](https://github.com/temporalio/sdk-typescript/issues/514). You may however easily encode the auth header by yourself before starting the Workflow, and decode that in your auth checking Activity. You should also embed details about the Workflow execution itself in that same encrypted header (eg. the Workflow Id, a checksum of args, approximate date/time of start, etc) so that a previous header value can't be reused to start a new Workflow Execution.

Note that this design is not the only possible solution, and other approaches may be more appropriate in some use cases. Before taking a decision, you should carefully analyze your threat model.

**Comment by YufeeXing** [comment]
> One possibility would be to call a local activity from your Workflow inbound interceptor. From that activity, you will be able to access environment variables and make calls to your external auth service.
> 
> You will however need to be careful to ensure that no sensitive data get written to the history. Note that, at the moment, TS SDK does not process [headers through Payload codecs](https://github.com/temporalio/sdk-typescript/issues/514). You may however easily encode the auth header by yourself before starting the Workflow, and decode that in your auth checking Activity. You should also embed details about the Workflow execution itself in that same encrypted header (eg. the Workflow Id, a checksum of args, approximate date/time of start, etc) so that a previous header value can't be reused to start a new Workflow Execution.
> 
> Note that this design is not the only possible solution, and other approaches may be more appropriate in some use cases. Before taking a decision, you should carefully analyze your threat model.

Thanks, @mjameswh. Got your point and will try.

**Comment by YufeeXing** [comment]
So, must use a local activity,right? Becaust there is no grpc request between the workflow and the activity, if all the grpc request need authentication.

**Comment by mjameswh** [comment]
> So, must use a local activity,right? Becaust there is no grpc request between the workflow and the local activity, if all the grpc request need authentication.

I mentioned Local Activities, but a regular Activity would also work. The main advantages of Local Activities are:

- Much lower latency
- Lower foot print in the Workflow History
- Guaranteed to be executed locally

For things such as "I want to get the value of an environment variable", using Local Activities is the obvious choice. We don't generally recommend using Local Activities for making call to external services, but they still sometime make sense if the service you are calling to is very fast, has very low probability of failure, and that retrying an operation is very cheap. I'm assuming this might be the case for your authorization service, but I may be wrong. I suggest you get a look at [this page](https://docs.temporal.io/activities#local-activity) for details on what Local Activities are and why you may want to use them over regular Activities. 

> How to define a local activity or how to judge a activity is local or not?

In TS SDK, the only difference in calling an Local Activity rather than an Activity is that you use `proxyLocalActivities(...)` rather than `proxyActivities(...)`. Also make sure that you set the `startToCloseTimeout` in `LocalActivityOptions` (there is a known bug in TS SDK up to 1.7.4 if you only set `scheduleToCloseTimeout`). That's it.

**Comment by YufeeXing** [comment]
Thanks, @mjameswh .
I think a regular Activity may not work, becasue the goal is to authenticate all the grpc requests. As I know, There is a grpc request between a Workflow and a regular Activity. So the Activity about authtication with env variable may be blocked. This may cause a deadlock?

**Comment by YufeeXing** [comment]
```
 import { toPayloads, DefaultPayloadConverter } from '@temporalio/common';

// in a interceptor
const token: string = await generateToken();
input.headers.Authorization = toPayloads(new DefaultPayloadConverter() ,token)![0];
return await next(input);
```
I think this may work, but I am not sure if it can use the string token in the toPayloads function because the defaultPayloadConverter only support byteArray and JSON.
