### ISSUE TITLE
[Bug] @temporalio/worker-1.7.4: Memory occupied by worker not getting released on AWS ECS (OS: Linux)

### ISSUE THREAD

**Issue by Naik1994** [temporalio/sdk-typescript#1192]
### What are you really trying to do?

We are using the Temporal SDK in one of our microservices deployed on an ECS container with a Linux OS. During load testing, we observed that the memory utilization gradually increased up to 50%, including heap memory, and it did not decrease until the server was restarted or stopped. Further investigation revealed that running the same codebase on a local system with Windows OS exhibited no issues. The heap memory was released promptly after 10 to 15 minutes. However, this behavior was not replicated when running the application on AWS environment.

However after passing the maxCachedWorkflows option as zero while creating the worker, the workflows are no longer being cached by the worker, and this has resolved the memory utilization issue. As a result, the heap memory is now getting released properly, and the problem is resolved temporarily as of now.

Request you to check and let us know if we need to do any specific configuration for container application to resolve above issue without passing **maxCachedWorkflows** option to worker.

await Worker.create({
    workflowsPath: require.resolve('./workflow'),
    connection,
    activities: createActivities(),
    taskQueue: 'test-'+process.env.stage,
    namespace: 'test',
    sinks: defaultSinks(workflowLogger),
    maxCachedWorkflows: 0
  })

### Describe the bug

We ran the hello world typescript sample shared by temporal on windows and observed that heap memory occupied while running activities got released automatically once the load gradually decreased on server.

1] without passing maxCachedWorkflows attribute in the option ->
numCachedWorkflows value was 100 since we triggered our code 100 times and heap memory got released slowly after the load is gone also it got released further once worker was idle for some time period.

![image](https://github.com/temporalio/sdk-typescript/assets/42242055/64ca0cd3-c332-40c4-aebe-67d5a2afb5d3)

![image](https://github.com/temporalio/sdk-typescript/assets/42242055/42110313-402d-476d-a718-8088f91b1873)

![image](https://github.com/temporalio/sdk-typescript/assets/42242055/594ea0b6-6dbc-4196-be65-4670f3771c27)

2] by passing maxCachedWorkflows attribute in the option ->

Workflows were not getting cached i.e numCachedWorkflows value was mostly zero, hence memory got released immediately after load decreased gradually.

![image](https://github.com/temporalio/sdk-typescript/assets/42242055/2657ceaa-c9c2-4182-8ada-33d125f6bf5a)

### Environment/Versions

Below is the configuration we are using for our own application.
- OS and processor: [Linux]
- SDK version: 
    "@temporalio/activity": "^1.7.4",
    "@temporalio/client": "^1.7.4",
    "@temporalio/worker": "^1.7.4",
    "@temporalio/workflow": "^1.7.4"
- We have deployed our containerized application on AWS ECS with Node image 16.4.1

**Comment by Naik1994** [comment]
We are not using the maxCachedWorkflows setting by default. Initially, we deployed our application without it, but then we observed that memory utilization increased during load testing. We monitored the system for 2-3 days after the load test, but the memory consumed during that period was not being released.

To address the memory issue, we decided to use the maxCachedWorkflows setting and set it to zero. After this change, we noticed that the occupied memory was getting released within 10-15 minutes after the load test. However, as a trade-off, we also observed an increase in CPU consumption.

Below are the graph screenshots for your reference, which we tested over the last week.
1] When tested without using the maxCachedWorkflows setting, the average memory utilization was around 34% for a couple of days. However, it decreased once we restarted the server.

![image](https://github.com/temporalio/sdk-typescript/assets/42242055/5d6e6d0e-924f-40a5-a3a1-18d44dbdd3ad)

2] When we tested using the maxCachedWorkflows setting set to 0, memory utilization was indeed released within 10-15 minutes after the load test. However, we observed that the average CPU utilization went above 100%, indicating a significant increase in CPU usage.

![image](https://github.com/temporalio/sdk-typescript/assets/42242055/3c781890-d7dc-455f-8566-b4a2bb6c0083)

However, in scenario 1, the application is functioning well on a local machine with Windows OS, and the heap memory is getting released as expected, even with cached workflows (please refer to the screenshots shared in the first thread). 

Please check and let us know if we are missing any configurations or if this is the default behavior. Even if it is the expected behavior, I'm concerned that at some point we will experience 100% memory utilization, which could crash the application, as the memory utilization has stabilized at a higher rate.

**Comment by mjameswh** [comment]
First of all, I strongly recommend that you update your `@temporalio/*` dependencies to 1.8.2. The 1.8.0 release introduced several performance related improvements. I also recommend that you enable the `WorkerOptions.reuseV8Context` option on your Worker, as this greatly reduce both memory usage and CPU usage.

If unspecified, `maxCachedWorkflows` defaults to 250 wf per GB of heap memory (that is up to TS SDK 1.7.4; the exact formula changed in 1.8.0, see [here](https://github.com/mjameswh/sdk-typescript/blob/08958f03fa30555ae3511dcb555cb3b56fcbee9c/packages/worker/src/worker-options.ts#L299-L300) for details). This is generally appropriate for day-to-day development; we however recommend that you explicitly configure `maxCachedWorkflows` in production environment, based on your specific application needs. Correctly tuning this involves performance testing.

Disabling workflow caching can be very detrimental for the performance of both your workers and your Temporal cluster. That is definitely not something you want to do in production.

> Initially, we deployed our application without it, but then we observed that memory utilization increased during load testing.

This is expected. The cache size will increase until it contains `maxCachedWorkflows`. From that point on, least recently used workflows will get evicted, so that you never have more than `maxCachedWorkflows` workflows in heap. At that point, memory usage should stabilize.

> We monitored the system for 2-3 days after the load test, but the memory consumed during that period was not being released. [...] However, in scenario 1, the application is functioning well on a local machine with Windows OS, and the heap memory is getting released as expected, even with cached workflows (please refer to the screenshots shared in the first thread).

Note that in your Windows screenshots, in your first message, the number of cached workflows is _not_ going down, even after the system has been idle for some time. The cache remains steadily at 100 wfs, and yet actual memory usage comes down to ~70 MB. The workflow cache has an LRU semantic. I'm not saying that a memory leak is impossible, but as far as I can see, the metrics you expose are coherent with the expected behavior.

Why then is the memory usage not going down in ECS's memory usage graph when workflow caching is enabled, while it does on Windows or when workflow caching is disabled? I have several possible factors in mind that may contribute to this apparent incoherency, but essentially all of it comes down to the way generational garbage collection works, and the fact that Windows and Linux manage memory differently.

>  I'm concerned that at some point we will experience 100% memory utilization, which could crash the application, as the memory utilization has stabilized at a higher rate.

I understand your concern. Workflows are not the only contributor to your process' memory usage. Activities and various other things running in that process/container may also require memory. Avoiding out-of-memory situations require finding a proper balance between all of these.

**Comment by Naik1994** [comment]
@mjameswh thanks for the support. We did test by upgrading all temporalio sdk libraries to latest version and enabling `reuseV8Context`, setting `maxCachedWorkflows` to 300 (just to see the behavior) and observed CPU utilization is below 100% however memory utilization is at 25% but stabilized. Does that mean memory will be at 25% and increasing as in when new workflows being executed?

![image](https://github.com/temporalio/sdk-typescript/assets/42242055/c281c026-deda-421c-9d7b-f164ff10a96d)

FYI, without enabling above settings default value of `maxCachedWorkflows` on Linux OS on AWS was set to 158 and on windows OS of local machine was 914. Meanwhile we will try to modify configuration and check the behavior further.

**Comment by mjameswh** [comment]
>  Does that mean memory will be at 25% and increasing as in when new workflows being executed?

If that 25% memory usage actually represents the state where your workflow cache is full, then yes, memory usage should indeed stay relatively stable (variations are to be expected). If however that 25% correspond to your workflow cache currently containing only 100 workflows, and you allow your cache to grow to 300 workflows, then memory usage will increase when you'll start more workflows, until the cache reaches its full capacity.

Try running a few hundreds of workflows (I'd say at least twice the number you specified in `maxCachedWorkflows`). That will ensure that the cache reaches its full capacity. At that point, you be get a better view of how much memory your cache is really taking.

Note that the memory footprint of a single cached workflow really depends on the workflow code and the libraries used by that workflow. That's why you really need to measure this with your actual workflow.

**Comment by mjameswh** [comment]
@Naik1994 I'm closing this ticket, as there is nothing to do on our side.

Feel free to continue the discussion if you still need help. You may also get help through our [Slack community](https://t.mp/slack) or our [community forum](https://community.temporal.io/).
