### ISSUE TITLE
Cron job getting scheduled after deployment and Terminated automatically after 1 minute or so  

### ISSUE THREAD

**Issue by Naik1994** [temporalio/sdk-typescript#1201]
@mjameswh Request you to check and suggest on below issue.

We have written a cron job using temporal workflow which executes half an hour once. We have not written a separate worker for this job workflow instead using the one namespace and one task queue to perform API calls and this JOB. Also, our application is running on AWS ECS with 4 default tasks (not sure if this will have any impact on scheduled job).

As in when we deploy our code on ECS container, cron is getting scheduled properly however getting terminated automatically after some time before execution. We tried to enable `workflowRunTimeout` and `workflowTaskTimeout` settings however sometime cron executed and terminated inbetween and sometimes it terminated immediatly after scheduling.

schedular settings used =>
`await client.start("cronJob", {
      taskQueue: 'test',
      workflowId: uuid(),
      cronSchedule: '*/30 * * * *',
      workflowRunTimeout: '86400000',
      workflowTaskTimeout: '300000',
      args: [uuid4()]
})`

Failure events captured in UI =>
1] terminated within 1 minute of scheduling job with below event object:
{
  "eventId": "2",
  "eventTime": "2023-08-11T08:47:13.012448068Z",
  "eventType": "WorkflowExecutionTerminated",
  "version": "0",
  "taskId": "10560924366",
  "workerMayIgnore": false,
  "workflowExecutionTerminatedEventAttributes": {
    "reason": "",
    "details": {
      "payloads": []
    },
    "identity": "1@7c97cc146289"
  },
  "name": "WorkflowExecutionTerminated",
  "id": "2",
  "timestamp": "2023-08-11 UTC 08:47:13.01",
  "classification": "Terminated",
  "category": "workflow",
  "attributes": {
    "type": "workflowExecutionTerminatedEventAttributes",
    "reason": "",
    "details": {
      "payloads": []
    },
    "identity": "1@7c97cc146289"
  }
}

2] terminated in between while executing the job:
{
  "eventId": "2278",
  "eventTime": "2023-08-11T07:02:56.007332938Z",
  "eventType": "WorkflowTaskFailed",
  "version": "0",
  "taskId": "10560921210",
  "workerMayIgnore": false,
  "workflowTaskFailedEventAttributes": {
    "scheduledEventId": "2276",
    "startedEventId": "2277",
    "cause": "ForceCloseCommand",
    "failure": null,
    "identity": "history-service",
    "baseRunId": "",
    "newRunId": "",
    "forkEventVersion": "0",
    "binaryChecksum": "",
    "workerVersion": null
  },
  "name": "WorkflowTaskFailed",
  "id": "2278",
  "timestamp": "2023-08-11 UTC 07:02:56.00",
  "classification": "Failed",
  "category": "workflow",
  "attributes": {
    "type": "workflowTaskFailedEventAttributes",
    "scheduledEventId": "2276",
    "startedEventId": "2277",
    "cause": "ForceCloseCommand",
    "failure": null,
    "identity": "history-service",
    "baseRunId": "",
    "newRunId": "",
    "forkEventVersion": "0",
    "binaryChecksum": "",
    "workerVersion": null
  }
}

Please let us know if we need to enable any other settings or should we have a separate task queue created for this crons ?

**Comment by Naik1994** [comment]
@mjameswh any update on this ?

**Comment by mjameswh** [comment]
Hey! Sorry for the delay, I was at a company event for the week. By the way, for support questions, you should consider asking on either [our community forum](https://community.temporal.io/) or [our community Slack workspace](https://t.mp/slack).

I'm afraid I can't entirely explain what's wrong in the two cases you describe, given the information you provide. Still, let's see what we can extract from there.

In the first sample, the `identity: "1@7c97cc146289"` field suggests that the workflow execution was terminated by a client, before a workflow task ever got scheduled (ie. since the termination `eventId` is 2). I would try to compare that `identity` with the one from `WorkflowExecutionStarted` event, as this might help figuring out what happened.

In the second sample, this `WorkflowTaskFailed` event is artificially introduced by the Temporal History server node, with the `ForceCloseCommand` code. This happens when a workflow somehow exceeds some operational limit, for example if there are too many buffered events for that workflow, or if buffered events exceeds the maximum gRPC message size. To help figure what's happening, examine that workflow's history events between the previous `WorkflowTaskStarted` event (ie. the last one before event id 2276) and up to the `WorkflowTaskScheduled` event at id 2276. Do you have thousands of events in-between? Or do you have a few events in large payloads?

One last thing... I suggest you get a look at [Schedules](https://docs.temporal.io/workflows#schedule), which are much more powerful and easier to work with compared to legacy cron workflows.

**Comment by mjameswh** [comment]
@Naik1994 I'm closing this ticket, as there is nothing to do on our side.

Feel free to continue the discussion if you still need help. You may also get help through our [Slack community](https://t.mp/slack) or our [community forum](https://community.temporal.io/).
