### ISSUE TITLE
[Feature Request] Support Deno

### ISSUE THREAD

**Issue by vwkd** [temporalio/sdk-typescript#1285]
Add support for Deno.

It would be great if we could write code like in Deno, which offers native Web APIs like `fetch` and executes TypeScript without a build step.

**Comment by mjameswh** [comment]
Sure, we really wish to support Deno at some point. There’s no debate on it’s advantages.

However, getting there will require considerable efforts. For context, TS SDK heavily depends on Worker Threads, VMs, async hooks, promise hooks, native libraries, and many other node-specific APIs. Yes, Deno provides compatibility or alternatives for most of these APIs, but last time I checked, Deno's implementations were not complete enough to support the kind of low level stuff that TS SDK does. But I'm very happy to see that things are progressing in the right direction (welcome `ShadowRealm`!).

In practice, I expect that we'll probably need to rewrite/redesign several key components of the TypeScript SDK to get it to run reliably and efficiently on Deno. We may also need to redesign parts of the Core SDK, notably to allow it to be usable as a WASM module rather than a NAPI library.

It seems very unlikely that we'll be able to make this a thing in the upcoming year. For now, I will close this ticket, as we use a different system to track and prioritize this kind of long-term/large-scale objectives.
