### ISSUE TITLE
[Feature Request] Eliminate glue code

### ISSUE THREAD

**Issue by vwkd** [temporalio/sdk-typescript#1287]
### Is your feature request related to a problem? Please describe.

The TypeScript SDK does a great job hiding the magic that's going on under the hood to let us write colocated code in a single language that runs in different execution contexts in different places. For example, Activities run in a normal environment while Workflows run in a custom deterministic environment, Workers run server-side while Clients run client-side.

But we still need to write a fair bit of glue code to hook up the different parts, like proxy functions and type annotations. Maybe the TypeScript SDK does a better job than the other SDKs, but it still would be nice to eliminate the remaining glue code.

With all the underlying magic that's already happening, the glue code shouldn't be technically necessary. Also, the glue code doesn't really help in explaining the underlying magic, which is much better fit for English documentation.

#### Workflows and Activities

Import and call Workflows and Activities like regular functions instead of proxying them through glue code. The config could be passed as mandatory first argument at function call without specifying it at declaration. A bit like the `self` parameter at method declaration in Rust that's not passed at function call, but the other way around.

```ts
// workflows.ts
import { greet } from './activities';

export async function hello(name: string): Promise<string> {
 const greeting = await greet({
    startToCloseTimeout: '1 minute'
  }, name);

  return greeting;
}
```

```ts
// client.ts
import { hello } from './workflows';

const result = await hello({
  taskQueue: 'greetings-1',
  workflowId: 'hello-1',
}, 'Temporal');
```

#### Workers

Import and pass Workflows as arguments instead of specifying a path like already done for Activities.

```ts
// worker.ts
import { Worker } from "@temporalio/worker";
import * as workflows from "./workflows";
import * as activities from "./activities";

const worker = await Worker.create({
  identity: "worker-1",
  taskQueue: "greetings-1",
  workflows,
  activities,
});
```

### Additional context

**Comment by mjameswh** [comment]
Thanks for sharing your observations regarding how the developer experience of the Temporal TypeScript SDK could be improved. We recognize that some of the indirections required when making calls across different execution contexts may make your code feel a bit less natural.

I disagree however with your claim that _"with all the underlying magic that's already happening, the glue code shouldn't be technically necessary"_. It might be possible to bring different forms of glue code, with different compromises, but given that we have to compose with how the language itself is designed, I honestly don't see how it would be possible to "magically" avoid any form of glue code.

Would you mind provide more details on what you are suggesting, and how this would satisfy the following concerns?

> Import and call Workflows and Activities like regular functions instead of proxying them through glue code. The config could be passed as mandatory first argument at function call without specifying it at declaration.

- Your workflow/activity functions don't expect workflow/activity options as their first argument. How can `import` (i.e. the JavaScript/TypeScript construct) inserts these arguments into the signature of workflow/activity functions you import?

- When calling a workflow/activity function, how does code execution get diverted to a Temporal action (i.e. starting a workflow or scheduling an activity), rather than simply calling the workflow/activity function directly?

- How would this magic mechanism differentiate between importing a workflow/activity function (which needs to execute in a different execution context) and importing some utility functions (which needs to execute in the same execution context as the caller)?

> Import and pass Workflows as arguments instead of specifying a path like already done for Activities

- In TS SDK, Workflow code is delegated to a different thread (Worker Thread). Due to the fact that V8 itself is single threaded, anything that is exchanged across threads needs to be serialized. V8's serialization protocol can't serialize functions. Therefore, starting a worker thread necessarily implies loading files by their file path. If user is specifying workflows as actual function objects, how can we "transfer" that function to the worker thread execution context?

- The TS SDK also execute workflow code inside a deterministic sandbox, which prevents reading files from disk, not even to `import()` or `require()` a source file from workflow code. For that reason, we need all the code that might be loaded/executed from the workflow context to be preloaded and transformed so that it effectively become a single source file. That is the reason for the "workflow bundling" process. If user is specifying workflows as actual function objects, how can we "bundle" that function for use from the sandbox execution context?

**Comment by mjameswh** [comment]
Closing this for now, as it is not actionable as is. I'm open to discuss further improvements, but would need more concrete suggestions.
