### ISSUE TITLE
[Feature Request] Do not set workflow completion until after all coroutines have settled in the task

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-typescript#1421]
### Describe the solution you'd like

See https://github.com/temporalio/features/issues/481

**Comment by dandavison** [comment]
https://github.com/temporalio/sdk-core/pull/776 has been merged, and so this is unblocked. In `sdk-python` and `sdk-dotnet` that PR allows the https://github.com/temporalio/features/issues/481 requirement to be solved relatively easily, by changing lang so that they no longer drop post-terminal commands, as they had been doing.
