### ISSUE TITLE
[Bug] Set the correct worker binary ID

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#204]
At the moment we pass the SDK version as the default binary ID, we should use the WF bundle checksum and perhaps include activity code as part of the checksum.

**Comment by lorensr** [comment]
For worker/activity code, `require.cache` has all the file paths that have been loaded in the current process, which we could read the contents of from disk to hash. More discussion:

https://temporaltechnologies.slack.com/archives/C01FG4BRQVB/p1644440779397319?thread_ts=1644439575.727109&cid=C01FG4BRQVB

**Comment by cretz** [comment]
FWIW this same concern applies to Python too. I would like to avoid reading all files or even walking the disk stat'ing them if at all possible (ntm it presumes you are running somewhere with a disk, but we have already made that assumption). But if we had to, you can possibly just get a hash of file names and each file's mtime to avoid reading entire files.

**Comment by lorensr** [comment]
![image](https://user-images.githubusercontent.com/251288/153507206-2cc43a2f-4768-4849-bd9c-347d0b627cf9.png)

path & mtime sounds good.

**Comment by Sushisource** [comment]
I believe mtime will be quite unreliable in terms of being stable across different worker deployments which have the same code.

One of (perhaps the most) the common use cases here is "I just deployed a bunch of (the same) workers with this new stuff, they broke things, and I want to find/reset all workflows they messed up". So, ending up with a consistent id for all the workers in such a deployment is very desirable. 

The versioning stuff we're going to work on probably makes that a lot easier eventually, but that will always require some amount of manual specification by users, whereas this is ideally fully automatic (albeit less meaningful). 

So, to the extent we can make that scenario work automatically, I think it's worth even doing something like loading up and hashing files. Practically speaking I think it's pretty low cost since you're only doing it on startup and the size of user wf code isn't exactly huge in "hash these files" terms. We're still talking only a few hundred ms even using slow spinny disks with _megabytes_ of workflow code, which seems unlikely.

**Comment by lorensr** [comment]
> I believe mtime will be quite unreliable in terms of being stable across different worker deployments which have the same code.

Ah, good point

**Comment by cretz** [comment]
True. It's a bit gross, but so long as you can override I guess it'll be ok.

Also, some deployments/packages do codegen that they then import that might have a "generated at XX" comment on it that'll break the hash. If cheap enough to use machine representation instead of source representation (it'll by bytecode in Python), I think we should. But I don't see where that's available in Node and I don't think it's reasonable to add a parse step.

**Comment by bergundy** [comment]
I think what we do now is good enough (using sha sum of the workflow bundle and SDK version).

https://github.com/temporalio/sdk-typescript/blob/dc63e490a22655fbdfa9e7fce4fa6f6fe57f2c92/packages/worker/src/worker.ts#L161

We can reopen if anyone feels the current approach is lacking.
