### ISSUE TITLE
[Feature Request] Expose history size to Workflow code

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-typescript#357]
[As discussed on our community slack](https://temporalio.slack.com/archives/C01DKSMU94L/p1635615168067800), we'd like to expose the number of history events and the aggregated payloads size to via `WorkflowInfo` so Workflow authors can make smarter decisions for when to continue as new.

**Comment by calumpwebb** [comment]
can the same issue (or way of solving this) be used for other sdks? We're mainly using the Go SDK and would want workflow history size on there too.

**Comment by cretz** [comment]
Definitely. Once implementation is defined on how best to do this, we can put this information on `WorkflowInfo` in Go assuming it's readily available. Same for Java (we try to maintain parity across SDKs). I will open the issues once the details are a bit better defined.

**Comment by sw-yx** [comment]
are people able to use https://typescript.temporal.io/api/classes/proto.temporal.api.workflowservice.v1.workflowservice-1/#getworkflowexecutionhistory to get this?

**Comment by bergundy** [comment]
Yes but this isn't accessible to workflows

**Comment by lorensr** [comment]
Related: 

> We should give `Workflow.isContinueAsNewNeeded` flag to the SDKs. And it should be coming from the service.

https://temporaltechnologies.slack.com/archives/C01FT8U10GK/p1643400086752909?thread_ts=1643398281.925129&cid=C01FT8U10GK

**Comment by lorensr** [comment]
Corresponding sdk-features issue: https://github.com/temporalio/sdk-features/issues/16

**Comment by lorensr** [comment]
Length we can expose now, size is waiting on it being provided by the server, which should come soon.

**Comment by mjameswh** [comment]
> Length we can expose now, size is waiting on it being provided by the server, which should come soon.

Obtaining the history length from the SDK would already be a huge improvement.

Right now, in long running workflows, we need to "estimate" the history length so that we can `continueAsNew()` once we reach some arbitrary threshold. Determining an appropriate threshold is _per se_ the issue here: it can be simply assumed that you have to continue as new after 10000 events... Lower this number if your workflow deals with large payloads...

Estimating the history length, however, is the hard part at present. There is simply no good and simple way to do it.
