### ISSUE TITLE
[Feature Request] Add default value to workflowId

### ISSUE THREAD

**Issue by emmanuelvlad** [temporalio/sdk-typescript#454]
### Is your feature request related to a problem? Please describe.

The problem is that I import the package `crypto` in every file where I start a workflow, it creates redundant code where I need to set the parameter `workflowId` to `crypto.randomUUID()`

### Describe the solution you'd like

It will be nice to have `workflowId` default's value to `crypto.randomUUID()`. Removes some redundant code

### Additional context

There probably was a reason to remove the default value of `workflowId` but I don't know why (#387)

**Comment by lorensr** [comment]
Pro of having a default is, as you say, that it makes random ID code shorter/simpler. 

We used to have a default. I think it was removed in an effort to guide users toward using business-meaningful IDs instead of random IDs. Would that make sense to do in your use case? The benefits are:

- Can reduce risk of duplicate Workflows. For instance, if I want to make one Workflow per order, I'd use the `orderId`. Then, if it's still running and I try to create it again, it will fail.
- Removes the need to (and possible problems around) storing the generated `workflowId`.
- Easier to look up Workflow.

I'm personally inclined toward:

- Having a default uuidv4
- Using a business meaningful ID in all or most of the docs and samples

Then we both guide people toward using business IDs **and** allow users for whom UUIDs make sense to write simple/non-redundant code.

**Comment by sw-yx** [comment]
we had considered offering a default random id function but also rejected the idea given its not that useful. see internal slack

**Comment by bergundy** [comment]
I don't see us reverting back to providing a default `workflowId`, the rationale is in the PR linked above.
You should always use meaningful business IDs for workflow IDs in real world scenarios and the API should lead users in that direction.
