### ISSUE TITLE
[Feature Request] Allow webpack configuration

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#537]
### Is your feature request related to a problem? Please describe.

Users needing or wanting to configure webpack in various ways.
### Describe the solution you'd like

@mjameswh listed a couple ideas in https://github.com/temporalio/sdk-typescript/issues/516#issue-1162103439

> Allow users to apply more generic overrides to the Webpack config. For example, an optional property webpackConfigOverrides could be added to BundleOptions. If it is there, that property would be merged with the default/calculated Webpack configuration. Alternatively, it could be an override function, which receive the default/calculated Webpack configuration, and returns the modified configuration (this is much more flexible, and easier from our point of view, more harder to work with for developers). This is for example [how Gatsby works](https://www.gatsbyjs.com/docs/how-to/custom-configuration/add-custom-webpack-config/). This approach would not only solve the current issue, but also provide a way to deal with many other very custom needs that developers may have (think of.. Hey guys! We would like to use [define](https://webpack.js.org/plugins/define-plugin/) for our workflows 😄 ) However, this would be more complex for developers to use, and arguably, there are not that many things that can be customized in Temporal's Webpack build process without risking breaking things.

**Comment by bergundy** [comment]
Related: https://github.com/temporalio/sdk-typescript/issues/483

**Comment by clarkdave** [comment]
It'd be great if we could adjust the webpack config!

In particular, my team would like to turn off type checking (i.e. pass the `transpileOnly` option to the `ts-loader`), because:

- it's not needed for us because we do all our typechecking in a separate process already
- it causes workers to crash for things like unused vars (annoying in development)
- it slows down the build (transpileOnly can be significantly faster)

It seems like it is just about possible to shim the (private) `WorkflowCodeBundler.prototype.compile` method, but it'd be a _lot_ easier if we could, say, have a method that allows to manipulate the webpack config before the compile takes place.

**Comment by bergundy** [comment]
> Is there any reason for transpileOnly not being enabled by default?

If there's a way to do that without losing the benefits you get from static type checking, I'd be totally on board.
In our samples we aim for ease of use, which is why we run with `ts-node`, I'd need to double check but if by using `ts-node` we get type checking, I think that'd be good enough.
I also checked on the `ts-loader` README and they recommend using `transpileOnly` with the [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin), we should look into that too.

Having said that, I'm pretty sure we'd still get requests to customize our bundler so we will probably end up making it more extensible for those (presumably) rare cases.

**Comment by Irvenae** [comment]
I see this issue got stale.
Maybe there is already a way to do this, but I would like to use absolute paths in my application instead of relative ones.
However, I can't get webpack configured to include my src directory as search path.

Is this possible in a way?

**Comment by bergundy** [comment]
Looks like this isn't possible today, we'll prioritize this and hopefully get to it soon.
