### ISSUE TITLE
[Bug] Parent workflow doesn't fail when child workflow encounters WorkflowExecutionAlreadyStartedError

### ISSUE THREAD

**Issue by dutabado** [temporalio/sdk-typescript#586]
### What are you really trying to do?

Ensure workflows properly exit and don't stay in the Running state indefinitely.

### Describe the bug

If a workflow, `ParentWorkflow` attempts to execute a `ChildWorkflow`, but uses the same workflow ID as an already executing instance of `ChildWorkflow`, the 2nd instance will fail as expected with `WorkflowExecutionAlreadyStartedError`. However, the `ParentWorkflow` instance that attempted to spawn the 2nd child workflow remains in the `Running` state indefinitely and never exits. Even if the first instance of `ChildWorkflow` completes, and the workflow is restarted, it remains stuck in Running.

### Minimal Reproduction

```typescript
import { sleep, executeChild } from '@temporalio/workflow';

export async function parentWorkflow(): Promise<string> {
  return await executeChild('childWorkflow', { 
    workflowId: 'childWorkflowId', // <-- intentionally static
  }
}

export async function childWorkflow(): Promise<void> {
  sleep(60000);
}
```

Launch two workflows concurrently
```bash
tctl workflow start --workflow_type parentWorkflow
tctl workflow start --workflow_type parentWorkflow
```

### Environment/Versions

- OS and processor: M1 Mac running Monterray 12.2.1
- Temporal Version: Typescript SDK 0.19.2
- Are you using Docker or Kubernetes or building Temporal from source? Docker

**Comment by bergundy** [comment]
Thanks @dutabado we'll fix this soon

**Comment by lorensr** [comment]
## Failing Task vs Execution

Normally when errors are thrown from Workflows, they fail the Task, so that the dev can either:

1. notice a logic bug and update the code, and existing Workflows will advance
2. figure out that they want the Execution to fail, and update the code to instead throw a `TemporalFailure`

We could make `WorkflowExecutionAlreadyStartedError` fail the Execution by extending `TemporalFailure` instead of `Error`, but I'm inclined to leave it as `Error`, so that they can go through the normal flow, as it might be a fixable logic bug.

## When should Worker give up on starting tasks

Normally core stops starting tasks after the first task failure, like:

```ts
export async function parentWorkflow(): Promise<string> {
  throw new Error('This is an error');
}
```

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/251288/163261433-97caa7fc-998c-46df-a9d1-4608aec8552d.png">

But in this case (error thrown from `executeChild`), it stops after two:

<img width="1687" alt="image" src="https://user-images.githubusercontent.com/251288/163260893-23f1c5fa-880f-4f29-a79c-d9ca4964d0a8.png">

Why is that?

**Comment by bergundy** [comment]
@lorensr according to @mfateev `WorkflowExecutionAlreadyStartedError` should extend `TemporalFailure` and fail the workflow.
That's why this issue was created in the first place.
