### ISSUE TITLE
[Feature Request] Change nonRetryable constructor param

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#587]
I really dislike negated boolean variable names, as I find them much more difficult to think about than the unnegated form. In the below constructors, I'd like to change `nonRetryable` (default false) to `retryable` (default true). Thoughts?

<img width="849" alt="image" src="https://user-images.githubusercontent.com/251288/163307289-62215c98-cd6a-4cdf-8367-89c754a6395b.png">

<img width="618" alt="image" src="https://user-images.githubusercontent.com/251288/163307319-78aa2deb-061b-4c6d-adb1-c90e14c71f4b.png">

**Comment by bergundy** [comment]
If we change this now it'd be a critical backwards incompatible change.
I think it's too late at this point.

**Comment by lorensr** [comment]
Like you feel it's too much to ask current users to find all the instances and flip the boolean when they upgrade the SDK?

**Comment by cretz** [comment]
> Like you feel it's too much to ask current users to find all the instances and flip the boolean when they upgrade the SDK?

I kinda feel that way. If it was a property on an object, the name change would be obvious, but since it's an unnamed parameter it can be hard to know. FWIW, "non-retryable" is common Temporal nomenclature, so while the double negative may be personally annoying, it does fit with the rest of the Temporal ecosystem.
