### ISSUE TITLE
[Bug] Sink API appears to create circular JSON

### ISSUE THREAD

**Issue by alex-dixon** [temporalio/sdk-typescript#610]
### What are you really trying to do?
Send data through a sink and call JSON stringify on it on the receiving (sink) end.

### Describe the bug
When I call a sink with data and stringify the result on the receiving end I sometimes receive a `TypeError: Converting circular structure` type error. I do not appear to receive this error if I stringify the the data on the sending end, before it is sent through the sink (so it doesn't seem the data actually has a circular structure before entering the sink, but it does after?). 

### Minimal Reproduction
I've avoided creating this issue because haven't had time to set one set up.... :) I wanted to at least post the issue. I will try to recreate it in isolation. I'd expect it would be reproducible by calling any sink with a fair amount of data. I don't know for sure the size of the payload matters. The app I've seen this in has pretty rapid sink writes also.

### Environment/Versions

- OS and processor: Linux
- Temporal Version: 0.20.1
- Are you using Docker or Kubernetes or building Temporal from source?
Docker + Kubernetes + Temporal Cloud
`node:16-bullseye`

**Comment by bergundy** [comment]
This is a limitation of the [`postMessage`](https://nodejs.org/api/worker_threads.html#portpostmessagevalue-transferlist).
We use this API because the workflow runs in a worker thread and the sink function runs on the main Node.js thread.

See also these architecture diagrams:
- https://github.com/temporalio/sdk-typescript/blob/main/docs/arch.svg
- https://github.com/temporalio/sdk-typescript/blob/main/docs/activation.mermaid
