### ISSUE TITLE
Memory leak on the temporal worker side

### ISSUE THREAD

**Issue by viavdeyenk-mts** [temporalio/sdk-typescript#649]
## Description

Some times ago we began using the temporal SDK in our microservice product, but after some times we detected that temporal-worker containers are killed by "out of memory" reason. Then we started our investigation and found the potential leak problem: a lot of 'OperatorSubscriber' objects create on temporal-worker side,  but it never clean, and it make memory leak problem. Right now it's  just a theory, but we hope that you can help us with checking it.

## Expected Behavior

We are not detecting memory leak

## Actual Behavior

We are detecting memory leak

## Steps to Reproduce the Problem

1. Run and inspect the temporal worker (e.g. `node --inspect src/worker.js`)
2. Start expect the worker process via chrome devtools
3. Execute the temporal client in infinity loop (for generate persistent loading for worker)
4. A little while later intervals via chrome devtools take memory snapshots from the worker process
5. Compare last memory snapshot with preview: there are a lot of `OperatorSubscriber` objects between the snapshots, so we can make the conclusion, that temporal typescript SDK has a memory leak
  ![memory-leak-detection.png](https://raw.githubusercontent.com/viavdeyenk-mts/temporal-tssdk-demo-memory-leak/main/img/08-memory-leak-detection.png)

## Specifications

  - Version: 0.22.0
  - Platform: x86_64 GNU/Linux (distr: Ubuntu:20.04, core: 5.14)

-------------------------------------

## Help with reproduce

For comfort reproduce, we created [the separate repository](https://github.com/viavdeyenk-mts/temporal-tssdk-demo-memory-leak) for help and  describe the steps for representation the leak problem.

**Comment by HalfdanJ** [comment]
Stumbled into this issue since i've been hunting a memory leak in our temporal worker, and ran into an identical situation as the screenshot above (with the latest version of temporal sdk installed). 

<img width="1251" alt="image" src="https://github.com/temporalio/sdk-typescript/assets/227529/9a0a1527-80b0-4133-932a-6af5fbcddf17">

**Comment by jainshivsagar** [comment]
I am also facing the same memory leak issue. 
@bergundy Please help here & assist your help.

![image](https://github.com/user-attachments/assets/a460cac9-816b-4eff-a62a-ddba6309c7b5)

**Comment by bergundy** [comment]
I'll defer to @mjameswh, the current SDK maintainer.

**Comment by mjameswh** [comment]
@jainshivsagar Please open a new ticket.

Even though the symptoms might be the same, this is very unlikely to be the same case:
- The issue from May 2022 was an actual bug in the SDK, which was resolved back then.
- The message from June 2024 was due to incorrect cleanup of an `AsyncLocalStorage` in user code; that resulted in [this ticket](https://github.com/temporalio/sdk-typescript/issues/1432).
