### ISSUE TITLE
[Bug] Deprecate `temporalio` meta package

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#727]
`npm install temporalio` doesn't work with package managers that do [strict dependency resolution](https://github.com/temporalio/sdk-typescript/issues/421#issuecomment-1067196052) (don't support transitive deps) like pnpm and yarn3.

We could either:
- keep `temporalio`, and warn at the top of the README and on install to not use it if you're using such a package manager
- change our setup instructions and samples `package.json`s to install the direct packages:

  ```
  npm install @temporalio/{client,worker,workflow,activity,common}
  ```

I think the latter is simpler / will result in less confusion.

**Comment by bergundy** [comment]
No need to install common directly

**Comment by lorensr** [comment]
Update: we'll do both, including `npm deprecate temporalio "message"`: 

https://docs.npmjs.com/cli/v8/commands/npm-deprecate

How's this deprecation message?

```
Instead of installing `temporalio`, we recommend directly installing our packages: npm remove temporalio; npm install @temporalio/client @temporalio/worker @temporalio/workflow @temporalio/activity
```

Will show up in the "Author message" field:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/251288/177867313-df27cde2-2e0c-42e2-8bf1-e983eab2f2fc.png">

**Comment by bergundy** [comment]
SGTM

**Comment by cretz** [comment]
Question - how do other projects do "umbrella" packages like this? Might it make more sense to just have a simple index file for the `temporalio` that imports all of those packages instead? I figure reading "No need to install common directly" that transitive dependencies _are_ actually included if referenced?

**Comment by bergundy** [comment]
We can’t export everything from the umbrella package as is because of workflow sandbox limitations.
We can work around it but I still want to support using the individual packages and would rather be consistent in our docs and samples.

**Comment by cretz** [comment]
> We can’t export everything from the umbrella package as is because of workflow sandbox limitations.

I am confused, if I only import things from `@temporalio/workflow` in the sandbox, how does that affect what's referenced from `@temporalio`?

My other questions still stand. Restated:

1. How do other projects do "umbrella" packages like this?
2. Why "No need to install common directly"? If I use anything out of `@temporalio/common`, won't pnpm or yarn fail? If so, why are we ok with telling a user "you must install specific package if you use it with pnpm/yarn" for "common" but not the others?

It seems like the limitations of pnpm and yarn would apply to those installing w/ those package managers while those using npm can still use umbrella packages. I'm curious what other projects do here.

**Comment by bergundy** [comment]
I'll explain what I meant.

If we encourage using the umbrella (meta) package, we'll have code in samples and such that looks like:
```ts
import * as wf from '@temporalio/workflow'
// and
import * as wf from 'temporalio/workflow'
```

I'd like to avoid this confusion and have a single "blessed" way to import our packages.
I'd also like users only wanting to use the client not to have to install the worker's native dependencies, this will especially become important when we write a browser client.

The problem with transitive dependencies is that package managers like pnpm prevent using a dependency without explicitly installing it (e.g specifying in package.json), this is due to the way they organize the packages and work around node's default module resolution.

> How do other projects do "umbrella" packages like this?

From what I've seen, you always install the packages you use.

> Why "No need to install common directly"? If I use anything out of @temporalio/common, won't pnpm or yarn fail if I use the setup instructions that we're now using? If so, why are we ok with telling a user "you must install specific package if you use it with pnpm/yarn" for "common" but not the others?

If you use anything from common with pnpm and yarn, you'll fail (at runtime), this is an expected by users of these package managers. We re-export most of the relevant common utilities from the other packages so you rarely need to install common directly.

> It seems like the limitations of pnpm and yarn would apply to those installing w/ those package managers while those using npm can still use umbrella packages. I'm curious what other projects do here.

That's a valid point, we don't **have** to deprecate the meta package, I may be uneducated here but it seems like the node ecosystem is going towards the more strict package layout scheme and I'd rather steer users in the right direction. When pnpm and yarn3 users see `npm install temporalio` in our getting started guides they'll try the same with their package manager and fail.

**Comment by lorensr** [comment]
1. Apollo Client used to have a long list of packages to install. Now they re-export everything from the meta package:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/251288/178038461-7c457b15-5538-4bb3-8051-c5571976afba.png">

2. Most samples don't import from `@temporalio/common`, since most things are re-exported from the relevant client/activity/workflow package. I'll add to docs that use common (I think just custom data converters) to `npm install @temporalio/common`.

**Comment by cretz** [comment]
Thanks! That things are re-exported and the common package isn't directly referenced now makes sense. As for a "meta" package, I can understand not wanting that. All of my concerns/questions are handled.
