### ISSUE TITLE
Improve test server download resilience

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#811]
Currently:

- When there's a broken java test server release, it breaks users' automated testing.
- When the latest released version doesn't have the test server asset at all, it breaks our user's `npm install`.

![image](https://user-images.githubusercontent.com/251288/183937593-a3d725e5-95e6-4874-9e96-b27bef0b55ba.png)

Solution:

Either:
- We depend on latest test server to work (will be added to CI https://github.com/temporalio/sdk-java/issues/1358) and latest release to have the test server, or
- We add logic to the download script that tries previous versions if latest assets aren't present (helps with 2nd issue but not first)
- We decouple, and put the latest known working version on a CDN (helps with both issues, but feels like duplicate effort if sdk-java has CI). Related: #782

**Comment by bergundy** [comment]
Suggested fix after discussing with @Spikhalskiy is to point the `@temporalio/testing` package to a fixed test server version, that way there are no surprises.
Another option discussed was bundling the test server into the npm package but that'd increase the download size to 45 MB instead of 15 (and 60 or 75 MB when we have aarach64 releases).

#782 will help avoid rate limit exceeded errors.

**Comment by bergundy** [comment]
We can now rely on temporal.download to cache requests to GH so users don't get rate limited and we can control which version is served in the handler for that URL.
